from __future__ import annotations

import copy
import base64
import hashlib
import json
import sqlite3
import sys
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import ark_backup as backup  # noqa: E402
import ark_common as common  # noqa: E402
import ark_restore as restore  # noqa: E402
import ark_verify as verify  # noqa: E402


PYTHON_LOCK = (
    "# This file was autogenerated by uv via the following command:\n"
    "# uv pip compile requirements.in --generate-hashes -o requirements.lock\n"
    "applemusic-mcp==0.20.0 \\\n"
    "    --hash=sha256:" + "a" * 64 + " \\\n"
    "    --hash=sha256:" + "b" * 64 + "\n"
).encode("utf-8")


def npm_lock(resolved: str = "https://registry.npmjs.org/example-mcp/-/example-mcp-1.2.3.tgz") -> bytes:
    return (json.dumps({
        "name": "custom-node-wrapper",
        "version": "1.0.0",
        "lockfileVersion": 3,
        "packages": {
            "": {
                "name": "custom-node-wrapper",
                "version": "1.0.0",
                "dependencies": {"example-mcp": "^1.2.0"},
            },
            "node_modules/example-mcp": {
                "version": "1.2.3",
                "resolved": resolved,
                "integrity": "sha512-" + base64.b64encode(b"i" * 64).decode("ascii"),
            },
        },
    }, sort_keys=True) + "\n").encode("utf-8")


def local_item(recipe_type: str) -> dict:
    common_fields = {
        "id": f"default-{recipe_type}",
        "server": recipe_type,
        "profile": "default",
        "archivePrefix": f"local-mcp-projects/default-{recipe_type}/content",
        "target": {
            "kind": "home",
            "relativePath": f".local/share/{recipe_type}",
            "requiresExplicitMapping": False,
        },
        "argsPathRewrites": [],
        "envPathRewrites": [],
        "reauthorizationRequired": True,
        "portableState": [],
        "excludedAccountState": [],
    }
    if recipe_type == "python-uv-lock":
        common_fields.update({
            "commandRelativePath": ".runtime/bin/python",
            "argsTemplate": ["-m", "applemusic_readonly_mcp.server"],
            "runtimeRecipe": {
                "type": "python-uv-lock",
                "python": "3.11",
                "runtimeRelativePath": ".runtime",
                "lockFile": "requirements.lock",
                "installLocalPackage": True,
                "verification": {
                    "type": "python-import",
                    "module": "applemusic_readonly_mcp.server",
                },
            },
        })
    else:
        common_fields.update({
            "commandName": "node",
            "argsTemplate": ["C:/source/node_modules/example-mcp/index.js"],
            "argsPathRewrites": [{
                "index": 0,
                "relativePath": "node_modules/example-mcp/index.js",
            }],
            "runtimeRecipe": {
                "type": "node-npm-lock",
                "lockFile": "package-lock.json",
                "installMode": "npm-ci-ignore-scripts",
                "verification": {"type": "node-check", "argIndex": 0},
            },
        })
    return common_fields


def manifest_with(item: dict, lock_bytes: bytes) -> dict:
    item = copy.deepcopy(item)
    item["installation"] = common.build_local_mcp_installation(item, lock_bytes)
    lock_rel = f"{item['archivePrefix']}/{item['runtimeRecipe']['lockFile']}"
    return {
        "schemaVersion": "2.2",
        "options": {"profile": "basic"},
        "entries": [{
            "relPath": lock_rel,
            "sha256": hashlib.sha256(lock_bytes).hexdigest(),
            "artifactClass": "local-mcp-source",
        }],
        "externalRoots": [],
        "links": [],
        "softwareInventory": [],
        "projectMappings": [],
        "postRestoreActions": [],
        "coverageGaps": [],
        "providerSources": [],
        "localMcpProjects": [item],
    }


class LocalMcpInstallationTests(unittest.TestCase):
    def test_live_json_is_frozen_at_finalize_and_preflight_uses_payload(self):
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "jobs.json"
            source.write_text('{"revision":1}\n', encoding="utf-8")
            manifest = {
                "options": {}, "desktopConsistency": {}, "sanitized": [],
                "keptSecrets": [], "entries": [{
                    "relPath": "hermes/cron/jobs.json", "originPath": str(source),
                    "sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                    "size": source.stat().st_size, "type": "automation",
                    "artifactClass": "automation", "linkTarget": None,
                }],
            }
            source.write_text('{"revision":2}\n', encoding="utf-8")
            collector = SimpleNamespace(m=manifest, include_secrets=False)
            backup.prepare_live_json_snapshots(collector)
            entry = manifest["entries"][0]
            self.assertEqual(json.loads(entry["_payload"]), {"revision": 2})
            self.assertEqual(entry["snapshotMethod"], "finalize-json-point-in-time")
            source.write_text('{"revision":3}\n', encoding="utf-8")
            backup.preflight_sources(manifest)

    def test_root_peer_dependency_must_be_locked(self):
        data = json.loads(npm_lock())
        data["packages"][""]["peerDependencies"] = {"evil-peer-package": "^1.0.0"}
        self.assertIsNone(common.parse_npm_root_provenance(
            (json.dumps(data, sort_keys=True) + "\n").encode("utf-8")
        ))

    def test_manifest_cannot_disable_explicit_mapping_for_sensitive_home_target(self):
        item = local_item("node-npm-lock")
        manifest = manifest_with(item, npm_lock())
        manifest["localMcpProjects"][0]["target"] = {
            "kind": "home", "relativePath": ".ssh", "requiresExplicitMapping": False,
        }
        with self.assertRaises(SystemExit):
            restore.validate_manifest(manifest)

    def test_external_root_target_template_is_code_owned(self):
        manifest = manifest_with(local_item("node-npm-lock"), npm_lock())
        manifest["externalRoots"] = [{
            "id": "root-x", "sourcePath": "C:/source/.ssh",
            "archivePrefix": "external-roots/root-x", "targetTemplate": "~/.ssh",
            "includedBy": "external-root", "requiresExplicitMapping": False,
        }]
        with self.assertRaises(SystemExit):
            restore.validate_manifest(manifest)

    def test_general_absolute_link_cannot_target_ssh(self):
        with tempfile.TemporaryDirectory() as tmp:
            source_home = Path(tmp) / "source"
            target_home = Path(tmp) / "target"
            manifest = {"sourceUserHome": str(source_home), "externalRoots": []}
            entry = {"linkTarget": str(source_home / ".ssh")}
            destination = restore.mapped_link_target(
                entry, target_home / ".hermes" / "evil-link", manifest, target_home, {}
            )
            self.assertIsNone(destination)

    def test_fresh_checks_desktop_provider_external_and_project_targets(self):
        with tempfile.TemporaryDirectory() as tmp:
            home = Path(tmp) / "home"
            hermes = home / "AppData" / "Local" / "hermes"
            desktop = common.hermes_desktop_home_for_user(home, "windows")
            (desktop / "occupied").mkdir(parents=True)
            (desktop / "occupied" / "file").write_text("x", encoding="utf-8")
            provider = hermes / "plugins" / "memory"
            provider.mkdir(parents=True)
            (provider / "provider.py").write_text("x", encoding="utf-8")
            external = home / "external"
            project = home / "project"
            external.mkdir(parents=True)
            project.mkdir(parents=True)
            manifest = {
                "localMcpProjects": [],
                "externalRoots": [{
                    "id": "root-x", "targetTemplate": None,
                    "requiresExplicitMapping": True,
                }],
                "projectMappings": [{"id": "project-x"}],
            }
            state = restore.detect_fresh(
                home, hermes, manifest, {}, "windows",
                {"project-x": project}, {"root-x": external},
            )
            for part in ("hermes-desktop", "hermes-provider", "external-roots", "projects"):
                self.assertFalse(state[part]["fresh"], part)

            mac_home = Path(tmp) / "mac-home"
            mac_hermes = mac_home / ".hermes"
            mac_desktop = common.hermes_desktop_home_for_user(mac_home, "macos")
            mac_desktop.mkdir(parents=True)
            (mac_desktop / "occupied").write_text("x", encoding="utf-8")
            mac_state = restore.detect_fresh(
                mac_home, mac_hermes, {"localMcpProjects": [], "externalRoots": [],
                                      "projectMappings": []}, {}, "macos", {}, {},
            )
            self.assertFalse(mac_state["hermes-desktop"]["fresh"])

    def test_ms365_launch_suffix_is_bound_to_audited_package_and_version(self) -> None:
        item = {
            "argsTemplate": [
                "C:/source/node_modules/@softeria/ms-365-mcp-server/dist/index.js",
                "--preset", "mail,calendar",
            ],
            "argsPathRewrites": [{
                "index": 0,
                "relativePath": "node_modules/@softeria/ms-365-mcp-server/dist/index.js",
            }],
            "runtimeRecipe": {
                "type": "node-npm-lock",
                "verification": {"argIndex": 0},
            },
            "installation": {"packageProvenance": [{
                "package": "@softeria/ms-365-mcp-server",
                "version": "0.145.2",
            }]},
        }
        self.assertTrue(common.node_item_has_trusted_launch_args(item))
        rebuilt = restore._typed_local_mcp_args(item, Path("C:/target/ms365"))
        self.assertEqual(rebuilt[-2:], ["--preset", "mail,calendar"])
        item["argsTemplate"][-1] = "mail,calendar,files"
        self.assertFalse(common.node_item_has_trusted_launch_args(item))
        item["argsTemplate"][-1] = "mail,calendar"
        item["installation"]["packageProvenance"][0]["version"] = "0.145.3"
        self.assertFalse(common.node_item_has_trusted_launch_args(item))

    def test_python_custom_wrapper_keeps_embedded_source_and_only_pin_hash_evidence(self) -> None:
        manifest = manifest_with(local_item("python-uv-lock"), PYTHON_LOCK)
        installation = manifest["localMcpProjects"][0]["installation"]
        self.assertIsNone(installation["trustedSource"])
        self.assertEqual(installation["runtime"], {
            "name": "python", "version": "3.11", "packageManager": "uv",
            "recipeType": "python-uv-lock",
        })
        self.assertEqual(installation["embeddedSourceFallback"]["role"], "custom-project-source")
        self.assertEqual(installation["packageProvenance"], [{
            "type": "pypi-locked-requirement",
            "package": "applemusic-mcp",
            "version": "0.20.0",
            "hashes": ["sha256:" + "a" * 64, "sha256:" + "b" * 64],
            "role": "locked-dependency",
        }])
        self.assertNotIn("repository", json.dumps(installation))
        self.assertNotIn("resolved", json.dumps(installation))
        restore.validate_manifest(manifest)

    def test_node_exact_registry_entry_provenance_enables_trusted_source(self) -> None:
        lock_bytes = npm_lock()
        manifest = manifest_with(local_item("node-npm-lock"), lock_bytes)
        installation = manifest["localMcpProjects"][0]["installation"]
        package = installation["packageProvenance"][0]
        self.assertEqual(package["package"], "example-mcp")
        self.assertEqual(package["version"], "1.2.3")
        self.assertEqual(package["resolved"], "https://registry.npmjs.org/example-mcp/-/example-mcp-1.2.3.tgz")
        self.assertTrue(package["integrity"].startswith("sha512-"))
        self.assertEqual(installation["trustedSource"]["package"], package)
        restore.validate_manifest(manifest)

    def test_sec001_python_lock_rejects_all_installer_directives(self) -> None:
        directives = (
            "--index-url=https://evil.invalid/simple",
            "--extra-index-url https://evil.invalid/simple",
            "--find-links=https://evil.invalid/wheels",
            "--trusted-host evil.invalid",
            "--constraint=constraints.txt",
        )
        for directive in directives:
            with self.subTest(directive=directive):
                hostile = directive.encode() + b"\n" + PYTHON_LOCK
                self.assertIsNone(common.parse_hash_locked_requirements(hostile))
                with self.assertRaisesRegex(ValueError, "hash-locked"):
                    common.build_local_mcp_installation(
                        local_item("python-uv-lock"), hostile
                    )

        embedded = PYTHON_LOCK.replace(
            b"--hash=sha256:" + b"a" * 64,
            b"--hash=sha256:" + b"a" * 64 + b" --index-url=https://evil.invalid/simple",
        )
        self.assertIsNone(common.parse_hash_locked_requirements(embedded))

    def test_sec002_unsafe_or_unverified_npm_resolution_fails_closed(self) -> None:
        for url in (
            "http://registry.npmjs.org/example-mcp/-/example-mcp-1.2.3.tgz",
            "https://example.invalid/example-mcp-1.2.3.tgz",
            "file:///tmp/example-mcp.tgz",
        ):
            with self.subTest(url=url):
                with self.assertRaisesRegex(ValueError, "supported package lock"):
                    common.build_local_mcp_installation(
                        local_item("node-npm-lock"), npm_lock(url)
                    )

        missing_integrity = json.loads(npm_lock().decode())
        del missing_integrity["packages"]["node_modules/example-mcp"]["integrity"]
        linked = json.loads(npm_lock().decode())
        linked["packages"]["node_modules/example-mcp"] = {
            "resolved": "src/example-mcp", "link": True,
        }
        transitive_http = json.loads(npm_lock().decode())
        transitive_http["packages"]["node_modules/example-mcp"]["dependencies"] = {"child": "1.0.0"}
        transitive_http["packages"]["node_modules/child"] = {
            "version": "1.0.0",
            "resolved": "http://registry.npmjs.org/child/-/child-1.0.0.tgz",
            "integrity": "sha512-" + base64.b64encode(b"c" * 64).decode("ascii"),
        }
        for hostile in (missing_integrity, linked, transitive_http):
            with self.assertRaisesRegex(ValueError, "supported package lock"):
                common.build_local_mcp_installation(
                    local_item("node-npm-lock"),
                    (json.dumps(hostile) + "\n").encode(),
                )

    def test_generated_installation_document_is_guidance_only(self) -> None:
        manifest = manifest_with(local_item("python-uv-lock"), PYTHON_LOCK)
        document = backup.render_installation(manifest)
        self.assertIn("Target install path", document)
        self.assertIn("embedded", document.lower())
        self.assertIn("applemusic-mcp==0.20.0", document)
        self.assertIn("no repository URL inferred", document)
        self.assertIn("non-executable", document)

    def test_hostile_path_url_and_arbitrary_command_fields_are_rejected(self) -> None:
        base = manifest_with(local_item("node-npm-lock"), npm_lock())
        path_attack = copy.deepcopy(base)
        path_attack["localMcpProjects"][0]["installation"]["target"]["relativePath"] = "../../escape"
        url_attack = copy.deepcopy(base)
        package = url_attack["localMcpProjects"][0]["installation"]["packageProvenance"][0]
        package["resolved"] = "https://example.invalid/evil.tgz"
        command_attack = copy.deepcopy(base)
        command_attack["localMcpProjects"][0]["installation"]["command"] = "powershell evil"
        nested_command = copy.deepcopy(base)
        nested_command["localMcpProjects"][0]["installation"]["embeddedSourceFallback"]["command"] = "npm install"
        for hostile in (path_attack, url_attack, command_attack, nested_command):
            with self.assertRaises(SystemExit):
                restore.validate_manifest(hostile)

    def test_unknown_local_fields_sensitive_state_and_advisory_commands_are_rejected(self) -> None:
        base = manifest_with(local_item("python-uv-lock"), PYTHON_LOCK)
        unknown_local_field = copy.deepcopy(base)
        unknown_local_field["localMcpProjects"][0]["shell"] = "powershell evil"
        sensitive_state = copy.deepcopy(base)
        sensitive_state["localMcpProjects"][0]["portableState"] = [
            "state/.applemusic-mcp/chrome/Default/Network/Cookies"
        ]
        advisory_command = copy.deepcopy(base)
        advisory_command["postRestoreActions"] = [{
            "id": "run-anything", "required": True,
            "action": "run this", "commands": ["powershell evil"],
        }]
        for hostile in (unknown_local_field, sensitive_state, advisory_command):
            with self.assertRaises(SystemExit):
                restore.validate_manifest(hostile)

    def test_embedded_lock_is_rederived_and_tampering_is_rejected(self) -> None:
        lock_bytes = npm_lock()
        manifest = manifest_with(local_item("node-npm-lock"), lock_bytes)
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            item = manifest["localMcpProjects"][0]
            lock_path = root / Path(item["archivePrefix"]) / "package-lock.json"
            lock_path.parent.mkdir(parents=True)
            lock_path.write_bytes(lock_bytes)
            reader = restore.BackupReader(str(root), None)
            try:
                restore.validate_installation_evidence(reader, manifest)
                tampered = copy.deepcopy(manifest)
                tampered["localMcpProjects"][0]["installation"]["lock"]["sha256"] = "0" * 64
                with self.assertRaises(SystemExit):
                    restore.validate_installation_evidence(reader, tampered)
            finally:
                reader.close()

    def test_sec004_requires_explicit_mapping_is_never_auto_resolved(self) -> None:
        item = local_item("python-uv-lock")
        item["target"] = {
            "kind": "home", "relativePath": ".ssh",
            "requiresExplicitMapping": True,
        }
        with tempfile.TemporaryDirectory() as raw:
            home = Path(raw)
            self.assertIsNone(restore._local_mcp_target(item, home, {}, "linux"))
            explicit = home / "approved-mcp"
            self.assertEqual(
                restore._local_mcp_target(item, home, {item["id"]: explicit}, "linux"),
                explicit,
            )

    def test_sec005_executable_args_are_typed_and_non_injectable(self) -> None:
        python_base = manifest_with(local_item("python-uv-lock"), PYTHON_LOCK)
        node_base = manifest_with(local_item("node-npm-lock"), npm_lock())
        hostile_manifests = []
        for args in (["-c", "__import__('os').system('calc')"],
                     ["-m", "applemusic_readonly_mcp.server", "--token=secret"]):
            hostile = copy.deepcopy(python_base)
            hostile["localMcpProjects"][0]["argsTemplate"] = args
            hostile_manifests.append(hostile)
        node_eval = copy.deepcopy(node_base)
        node_eval["localMcpProjects"][0]["argsTemplate"] = ["-e"]
        hostile_manifests.append(node_eval)
        node_extra = copy.deepcopy(node_base)
        node_extra["localMcpProjects"][0]["argsTemplate"].append("--eval=evil")
        hostile_manifests.append(node_extra)
        for hostile in hostile_manifests:
            with self.assertRaises(SystemExit):
                restore.validate_manifest(hostile)

    def test_sec006_local_mcp_link_entries_are_rejected(self) -> None:
        manifest = manifest_with(local_item("python-uv-lock"), PYTHON_LOCK)
        item = manifest["localMcpProjects"][0]
        manifest["entries"].append({
            "relPath": f"{item['archivePrefix']}/src/linked.py",
            "sha256": None,
            "artifactClass": "link-topology",
            "linkTarget": "C:/Users/source/.ssh/id_rsa",
        })
        with self.assertRaisesRegex(SystemExit, "不允许任何 symlink"):
            restore.validate_manifest(manifest)

    def test_sec006_backup_collector_rejects_local_mcp_file_symlink(self) -> None:
        class FakeCollector:
            def __init__(self) -> None:
                self.m = {"entries": [], "coverageGaps": [], "excluded": []}

            def record_excluded(self, path: Path, reason: str) -> None:
                self.m["excluded"].append({"originPath": str(path), "reason": reason})

            def collect_file(self, *_args, **_kwargs) -> None:
                raise AssertionError("local MCP symlink reached collect_file")

        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            linked = root / "src" / "linked.py"
            linked.parent.mkdir()
            linked.write_text("placeholder\n", encoding="utf-8")
            collector = FakeCollector()
            with mock.patch.object(common, "is_link_like", side_effect=lambda path: path == linked):
                backup._collect_local_mcp_tree(collector, root, "local-mcp-projects/x/content", 0)
            self.assertEqual(
                collector.m["coverageGaps"][0]["class"], "local-mcp-link-unresolved"
            )
            self.assertEqual(
                collector.m["excluded"][0]["reason"], "local-mcp-link-not-portable"
            )

    def test_logic001_python_runtime_path_must_be_exactly_runtime(self) -> None:
        manifest = manifest_with(local_item("python-uv-lock"), PYTHON_LOCK)
        manifest["localMcpProjects"][0]["runtimeRecipe"]["runtimeRelativePath"] = "state"
        with self.assertRaisesRegex(SystemExit, "Python recipe"):
            restore.validate_manifest(manifest)

    def test_logic002_local_mcp_blocking_gap_cannot_hide_behind_basic_profile(self) -> None:
        manifest = manifest_with(local_item("python-uv-lock"), PYTHON_LOCK)
        manifest["options"]["profile"] = "basic"
        manifest["coverageGaps"] = [{
            "class": "local-stdio-command-unresolved", "path": "default:evil",
        }]
        with self.assertRaisesRegex(SystemExit, "coverage gap"):
            restore.validate_manifest(manifest)

    def test_logic003_fresh_checks_automatic_and_explicit_local_targets(self) -> None:
        automatic = local_item("python-uv-lock")
        explicit = local_item("node-npm-lock")
        explicit["id"] = "explicit-node"
        explicit["target"] = {
            "kind": "explicit", "relativePath": None,
            "requiresExplicitMapping": True,
        }
        with tempfile.TemporaryDirectory() as raw:
            home = Path(raw)
            auto_target = restore._local_mcp_target(automatic, home, {}, "linux")
            mapped_target = home / "mapped-node"
            auto_target.mkdir(parents=True)
            mapped_target.mkdir()
            fresh = restore.detect_fresh(
                home, home / ".hermes",
                {"localMcpProjects": [automatic, explicit]},
                {"explicit-node": mapped_target}, "linux",
            )
            occupied = {item["id"] for item in fresh["local-mcp-projects"]["occupiedTargets"]}
            self.assertEqual(occupied, {automatic["id"], "explicit-node"})
            self.assertFalse(fresh["local-mcp-projects"]["fresh"])

    def test_logic004_sandbox_only_exempts_and_verifies_rewritten_configs(self) -> None:
        item = local_item("python-uv-lock")
        manifest = {"localMcpProjects": [item], "entries": []}
        with tempfile.TemporaryDirectory() as raw:
            home = Path(raw)
            hermes = common.hermes_home_for_user(home)
            root = restore._local_mcp_target(item, home, {}, restore._target_platform())
            main_config = hermes / "config.yaml"
            main_config.parent.mkdir(parents=True)
            main_config.write_text(
                "mcp_servers:\n  python-uv-lock:\n"
                f"    command: '{restore._python_runtime_path(root, restore._target_platform())}'\n"
                "    args: [-m, applemusic_readonly_mcp.server]\n",
                encoding="utf-8",
            )
            unrelated = hermes / "profiles" / "unrelated" / "config.yaml"
            unrelated.parent.mkdir(parents=True)
            unrelated.write_text("tampered: true\n", encoding="utf-8")
            manifest["entries"] = [
                {"relPath": "hermes/config.yaml", "sha256": "0" * 64},
                {"relPath": "hermes/profiles/unrelated/config.yaml", "sha256": "1" * 64},
            ]
            failures = verify.check_sandbox(
                manifest, {"hermes", "local-mcp-projects"}, home
            )
            self.assertTrue(any(
                "hermes/profiles/unrelated/config.yaml" in failure for failure in failures
            ))
            self.assertFalse(any(
                failure == "沙箱恢复 hash 不一致: hermes/config.yaml" for failure in failures
            ))

    def test_sec007_memory_derived_log_exclusion_is_case_normalized(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            (root / "Memory-Generation-Logs").mkdir()
            collector = backup.Collector(
                {"entries": [], "excluded": [], "coverageGaps": [], "skills": []},
                SimpleNamespace(profile="basic", quiet=True), set(), False,
            )
            collector.walk_tree(
                root, "hermes-memory/.memory-tencentdb/memory-tdai", "hermes-memory",
                0, extra_skip=backup.MEMORY_DERIVED_DIRS, allow_memory_store=True,
            )
            self.assertEqual(collector.m["entries"], [])
            self.assertEqual(
                collector.m["excluded"][0]["reason"],
                "derived-memory-generation-audit-log",
            )

    def test_logic005_in_place_repairs_share_transactional_rollback(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            home = Path(raw)
            hermes = home / ".hermes"
            memory = home / ".memory-tencentdb"
            hermes.mkdir()
            memory.mkdir()
            env = hermes / ".env"
            gateway = memory / "tdai-gateway.standalone.yaml"
            env_original = "TDAI_DATA_DIR=/source/data\nMEMORY_TENCENTDB_GATEWAY_CMD=source-runtime\n"
            gateway_original = "data:\n  baseDir: /source/data\n"
            env.write_text(env_original, encoding="utf-8")
            gateway.write_text(gateway_original, encoding="utf-8")
            db = hermes / "projects.db"
            connection = sqlite3.connect(db)
            try:
                connection.execute("CREATE TABLE project_folders(project_id TEXT, path TEXT)")
                connection.execute("CREATE TABLE projects(id TEXT, primary_path TEXT)")
                connection.execute("INSERT INTO project_folders VALUES('p1','C:/source/project')")
                connection.execute("INSERT INTO projects VALUES('p1','C:/source/project')")
                connection.commit()
            finally:
                connection.close()
            manifest = {"projectMappings": [{
                "id": "p", "origins": [{
                    "kind": "projects.db", "profile": "default", "projectId": "p1",
                }],
            }]}
            conflicts = home / ".ark" / "restore-conflicts" / "test"
            changed: list[tuple[str, Path, bool]] = []
            restore.repair_hermes_memory_paths(home, hermes, conflicts, changed)
            restore.remap_projects_databases(
                manifest, hermes, {"p": home / "mapped"}, conflicts, changed
            )
            self.assertEqual(
                {rel for rel, _path, _had_old in changed},
                {
                    "hermes/.env",
                    "hermes-memory/.memory-tencentdb/tdai-gateway.standalone.yaml",
                    "hermes/projects.db",
                },
            )
            self.assertFalse(restore.rollback_changes(changed, conflicts))
            self.assertEqual(env.read_text(encoding="utf-8"), env_original)
            self.assertEqual(gateway.read_text(encoding="utf-8"), gateway_original)
            connection = sqlite3.connect(db)
            try:
                self.assertEqual(
                    connection.execute(
                        "SELECT path FROM project_folders WHERE project_id='p1'"
                    ).fetchone()[0],
                    "C:/source/project",
                )
            finally:
                connection.close()

    def test_logic006_each_external_absolute_arg_and_env_path_records_blocking_gap(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw) / "fixture-mcp"
            (root / "src" / "fixture").mkdir(parents=True)
            (root / "pyproject.toml").write_text("[project]\nname='fixture'\n", encoding="utf-8")
            (root / "requirements.lock").write_bytes(PYTHON_LOCK)
            (root / "src" / "fixture" / "server.py").write_text("READY=True\n", encoding="utf-8")
            runtime = root / ".runtime" / ("Scripts/python.exe" if sys.platform == "win32" else "bin/python")
            external_arg = Path(raw) / "outside" / "arg.json"
            external_env = Path(raw) / "outside" / "state"
            collector = SimpleNamespace(m={"coverageGaps": []})
            backup.collect_local_stdio_mcps(collector, [{
                "profile": "default",
                "_mcpSpecs": {"fixture": {
                    "command": str(runtime),
                    "args": ["-m", "fixture.server", str(external_arg)],
                    "env": {"FIXTURE_HOME": str(external_env)},
                }},
            }], 0)
            classes = [gap["class"] for gap in collector.m["coverageGaps"]]
            self.assertEqual(classes.count("local-stdio-absolute-arg-unmapped"), 1)
            self.assertEqual(classes.count("local-stdio-absolute-env-path-unmapped"), 1)
            self.assertNotIn("localMcpProjects", collector.m)


if __name__ == "__main__":
    unittest.main()
